/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ft9ZASGIcym
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import Link from "next/link"
import { Button } from "../../components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "../../components/ui/sheet"

export function BaseLayout() {
  return (
    <div className="grid md:grid-cols-[280px_1fr] w-full min-h-screen">
      <div className="bg-gray-100 dark:bg-gray-800 hidden md:block">
        <div className="flex flex-col h-full">
          <div className="flex h-16 items-center px-6 border-b border-gray-200 dark:border-gray-700">
            <p className="flex items-center gap-2 font-semibold">
              <MountainIcon className="h-6 w-6" />
              <span className="text-gray-900 dark:text-gray-50">Acme Inc</span>
            </p>
          </div>
          <nav className="flex-1 py-4">
            <ul className="grid gap-1">
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <HomeIcon className="h-5 w-5" />
                  Home
                </p>
              </li>
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <UserIcon className="h-5 w-5" />
                  About
                </p>
              </li>
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <BriefcaseIcon className="h-5 w-5" />
                  Services
                </p>
              </li>
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <MailIcon className="h-5 w-5" />
                  Contact
                </p>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <div className="flex flex-col">
        <header className="flex h-16 items-center justify-between border-b border-gray-200 bg-white px-4 dark:border-gray-700 dark:bg-gray-950 md:hidden">
          <p className="flex items-center gap-2 font-semibold">
            <MountainIcon className="h-6 w-6" />
            <span className="text-gray-900 dark:text-gray-50">Acme Inc</span>
          </p>
          <Sheet>
            <SheetTrigger asChild>
              <Button size="icon" variant="ghost">
                <MenuIcon className="h-6 w-6 text-gray-600 dark:text-gray-400" />
                <span className="sr-only">Toggle navigation</span>
              </Button>
            </SheetTrigger>
            <SheetContent className="bg-white dark:bg-gray-950" side="left">
              <div className="flex h-16 items-center px-6 border-b border-gray-200 dark:border-gray-700">
                <Link className="flex items-center gap-2 font-semibold" href="#">
                  <MountainIcon className="h-6 w-6" />
                  <span className="text-gray-900 dark:text-gray-50">Acme Inc</span>
                </Link>
              </div>
              <nav className="flex-1 py-4">
                <ul className="grid gap-1">
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <HomeIcon className="h-5 w-5" />
                      Home
                    </p>
                  </li>
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <UserIcon className="h-5 w-5" />
                      About
                    </p>
                  </li>
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <BriefcaseIcon className="h-5 w-5" />
                      Services
                    </p>
                  </li>
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <MailIcon className="h-5 w-5" />
                      Contact
                    </p>
                  </li>
                </ul>
              </nav>
            </SheetContent>
          </Sheet>
        </header>
        <main className="flex-1 p-4 md:p-6">
          <div className="prose prose-stone dark:prose-invert">
            <h1>Welcome to Acme Inc</h1>
            <p>
              We are a leading provider of innovative solutions for businesses of all sizes. Our team of experts is
              dedicated to helping you achieve your goals and reach new heights.
            </p>
            <h2>Our Services</h2>
            <ul>
              <li>Web Development</li>
              <li>Mobile App Development</li>
              <li>Digital Marketing</li>
              <li>IT Consulting</li>
            </ul>
            <h2>Contact Us</h2>
            <p>Get in touch with us today to learn more about how we can help your business succeed.</p>
            <p>
              Email:
              <a href="#">info@acmeinc.com</a>
            </p>
            <p>
              Phone:
              <a href="#">+1 (234) 567-890</a>
            </p>
          </div>
        </main>
      </div>
    </div>
  )
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
