/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ft9ZASGIcym
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import Link from "next/link"
import { Button } from "../../components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "../../components/ui/sheet"
import { MountainIcon, HomeIcon, UserIcon, BriefcaseIcon, MailIcon, MenuIcon } from '../ui/icon'

export function BaseLayout({ children } : { children: React.ReactNode }) {
  return (
    <div className="grid md:grid-cols-[280px_1fr] w-full min-h-screen">
      <div className="bg-gray-100 dark:bg-gray-800 hidden md:block">
        <div className="flex flex-col h-full">
          <div className="flex h-16 items-center px-6 border-b border-gray-200 dark:border-gray-700">
            <p className="flex items-center gap-2 font-semibold">
              <MountainIcon className="h-6 w-6" />
              <span className="text-gray-900 dark:text-gray-50">Acme Inc</span>
            </p>
          </div>
          <nav className="flex-1 py-4">
            <ul className="grid gap-1">
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <HomeIcon className="h-5 w-5" />
                  Home
                </p>
              </li>
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <UserIcon className="h-5 w-5" />
                  About
                </p>
              </li>
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <BriefcaseIcon className="h-5 w-5" />
                  Services
                </p>
              </li>
              <li>
                <p
                  className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                  <MailIcon className="h-5 w-5" />
                  Contact
                </p>
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <div className="flex flex-col">
        <header className="flex h-16 items-center justify-between border-b border-gray-200 bg-white px-4 dark:border-gray-700 dark:bg-gray-950 md:hidden">
          <p className="flex items-center gap-2 font-semibold">
            <MountainIcon className="h-6 w-6" />
            <span className="text-gray-900 dark:text-gray-50">Acme Inc</span>
          </p>
          <Sheet>
            <SheetTrigger asChild>
              <Button size="icon" variant="ghost">
                <MenuIcon className="h-6 w-6 text-gray-600 dark:text-gray-400" />
                <span className="sr-only">Toggle navigation</span>
              </Button>
            </SheetTrigger>
            <SheetContent className="bg-white dark:bg-gray-950" side="left">
              <div className="flex h-16 items-center px-6 border-b border-gray-200 dark:border-gray-700">
                <p className="flex items-center gap-2 font-semibold">
                  <MountainIcon className="h-6 w-6" />
                  <span className="text-gray-900 dark:text-gray-50">Acme Inc</span>
                </p>
              </div>
              <nav className="flex-1 py-4">
                <ul className="grid gap-1">
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <HomeIcon className="h-5 w-5" />
                      Home
                    </p>
                  </li>
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <UserIcon className="h-5 w-5" />
                      About
                    </p>
                  </li>
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <BriefcaseIcon className="h-5 w-5" />
                      Services
                    </p>
                  </li>
                  <li>
                    <p
                      className="flex items-center gap-3 px-6 py-2 text-gray-600 hover:bg-gray-200 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-50">
                      <MailIcon className="h-5 w-5" />
                      Contact
                    </p>
                  </li>
                </ul>
              </nav>
            </SheetContent>
          </Sheet>
        </header>
        <main className="flex-1 p-4 md:p-6">
          <div className="prose prose-stone dark:prose-invert">
            <main>{children}</main>
          </div>
        </main>
      </div>
    </div>
  )
}
