/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/g9mQFXw4lbV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.75rem;
}
**/

export function BoxLayout({ left, right } : { left: React.ReactNode, right: React.ReactNode }) {
  return (
    <div className="container mx-auto px-4 py-12 md:px-6 lg:py-16">
      <div className="grid grid-cols-1 2xl:grid-cols-2 gap-8">
        <div className="space-y-8">
          <main>{left}</main>
        </div>
        <div className="space-y-8">
          <main>{right}</main>
        </div>
      </div>
    </div>
  )
}