/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YaaHFcpU03v
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.75rem;
}
**/
import Link from "next/link"
import { Input } from "../../components/ui/input"
import { Textarea } from "../../components/ui/textarea"
import { Button } from "../../components/ui/button"

export function BoxLayout() {
  return (
    <div className="container mx-auto px-4 py-12 md:px-6 lg:py-16">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="space-y-8">
          <div className="bg-white rounded-lg shadow-md p-6 dark:bg-gray-800">
            <h3 className="text-xl font-semibold mb-4">Featured Article</h3>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl eget ultricies tincidunt, nisl
              nisl aliquam nisl, eget aliquam nisl nisl eget nisl.
            </p>
            <p className="inline-flex items-center text-primary hover:text-primary-600 transition-colors">
              Read More
              <ArrowRightIcon className="ml-2 w-4 h-4" />
            </p>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 dark:bg-gray-800">
            <h3 className="text-xl font-semibold mb-4">Latest Updates</h3>
            <ul className="space-y-4">
              <li>
                <h4 className="font-medium mb-2">New Feature Release</h4>
                <p className="text-gray-500 dark:text-gray-400">
                  We've just launched a new feature that will revolutionize your workflow.
                </p>
              </li>
              <li>
                <h4 className="font-medium mb-2">Bug Fixes</h4>
                <p className="text-gray-500 dark:text-gray-400">
                  We've addressed several critical bugs in our latest update.
                </p>
              </li>
            </ul>
          </div>
        </div>
        <div className="space-y-8">
          <div className="bg-white rounded-lg shadow-md p-6 dark:bg-gray-800">
            <h3 className="text-xl font-semibold mb-4">Testimonials</h3>
            <div className="grid gap-6">
              <div className="bg-gray-100 rounded-lg p-4 dark:bg-gray-700">
                <p className="text-gray-500 dark:text-gray-400 mb-4">
                  "This product has been a game-changer for our business. We\n highly recommend it!"
                </p>
                <div className="flex items-center">
                  <img
                    alt="Avatar"
                    className="rounded-full mr-4"
                    height={40}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "40/40",
                      objectFit: "cover",
                    }}
                    width={40}
                  />
                  <div>
                    <h4 className="font-medium">John Doe</h4>
                    <p className="text-gray-500 dark:text-gray-400">CEO, Acme Corp</p>
                  </div>
                </div>
              </div>
              <div className="bg-gray-100 rounded-lg p-4 dark:bg-gray-700">
                <p className="text-gray-500 dark:text-gray-400 mb-4">
                  "I've been using this product for years and it's been\n invaluable to my business."
                </p>
                <div className="flex items-center">
                  <img
                    alt="Avatar"
                    className="rounded-full mr-4"
                    height={40}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "40/40",
                      objectFit: "cover",
                    }}
                    width={40}
                  />
                  <div>
                    <h4 className="font-medium">Jane Smith</h4>
                    <p className="text-gray-500 dark:text-gray-400">Founder, Widgets Inc</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6 dark:bg-gray-800">
            <h3 className="text-xl font-semibold mb-4">Contact Us</h3>
            <form className="space-y-4">
              <Input name="Name" placeholder="Enter your name" />
              <Input name="Email" placeholder="Enter your email" type="email" />
              <Textarea name="Message" placeholder="Enter your message" />
              <Button type="submit">Submit</Button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
